from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.orm import Session
from typing import Optional
from datetime import datetime
import sys
import os

# Add shared directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', 'shared'))

from database import get_db
from app.schemas import (
    ActiveCounts, CustomerHistory, TopCustomers, RestaurantOrders,
    RestaurantRevenue, PopularMenuItems, StatusDistribution,
    DriverDeliveries, CancelledOrders, AverageOrderValue, PeakTimes
)
from shared.auth import get_current_user, require_role, UserRole
from services.reporting_service import ReportingService

router = APIRouter()

@router.get("/reports/active-counts", response_model=ActiveCounts)
async def get_active_counts(db: Session = Depends(get_db)):
    """Get total active customers, restaurants, and drivers"""
    reporting_service = ReportingService()
    return reporting_service.get_active_counts(db)

@router.get("/reports/customer-history/{customer_id}", response_model=CustomerHistory)
async def get_customer_history(
    customer_id: int,
    skip: int = 0,
    limit: int = 100,
    customer_name: Optional[str] = Query(None, description="Optional search by customer name (ILIKE)"),
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Get detailed history of all orders placed by a customer"""
    if current_user.role == UserRole.CUSTOMER and current_user.id != customer_id:
        raise HTTPException(status_code=403, detail="Not authorized to view this customer's history")
    
    reporting_service = ReportingService()
    return reporting_service.get_customer_history(db, customer_id, skip, limit, customer_name)

@router.get("/reports/top-customers", response_model=TopCustomers)
async def get_top_customers(
    limit: int = 5,
    db: Session = Depends(get_db),
    current_user = Depends(require_role(UserRole.ADMIN))
):
    """Get top customers with highest order frequency"""
    reporting_service = ReportingService()
    return reporting_service.get_top_customers(db, limit)

@router.get("/reports/restaurant-orders", response_model=RestaurantOrders)
async def get_restaurant_orders(
    restaurant_id: int,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Get number of orders received and fulfilled by a restaurant"""
    if current_user.role == UserRole.RESTAURANT and current_user.id != restaurant_id:
        raise HTTPException(status_code=403, detail="Not authorized to view this restaurant's data")
    
    reporting_service = ReportingService()
    return reporting_service.get_restaurant_orders(db, restaurant_id, start_date, end_date)

@router.get("/reports/restaurant-revenue", response_model=RestaurantRevenue)
async def get_restaurant_revenue(
    restaurant_id: int,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Get breakdown of total revenue generated by a restaurant"""
    if current_user.role == UserRole.RESTAURANT and current_user.id != restaurant_id:
        raise HTTPException(status_code=403, detail="Not authorized to view this restaurant's data")
    
    reporting_service = ReportingService()
    return reporting_service.get_restaurant_revenue(db, restaurant_id, start_date, end_date)

@router.get("/reports/popular-menu-items", response_model=PopularMenuItems)
async def get_popular_menu_items(
    limit: int = 10,
    db: Session = Depends(get_db)
):
    """Get most ordered menu items across all restaurants"""
    reporting_service = ReportingService()
    return reporting_service.get_popular_menu_items(db, limit)

@router.get("/reports/order-status-distribution", response_model=StatusDistribution)
async def get_order_status_distribution(db: Session = Depends(get_db)):
    """Get distribution of order statuses"""
    reporting_service = ReportingService()
    return reporting_service.get_order_status_distribution(db)

@router.get("/reports/driver-deliveries", response_model=DriverDeliveries)
async def get_driver_deliveries(
    driver_id: int,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Get number of deliveries completed by a driver"""
    if current_user.role == UserRole.DRIVER and current_user.id != driver_id:
        raise HTTPException(status_code=403, detail="Not authorized to view this driver's data")
    
    reporting_service = ReportingService()
    return reporting_service.get_driver_deliveries(db, driver_id)

@router.get("/reports/cancelled-orders", response_model=CancelledOrders)
async def get_cancelled_orders(
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    db: Session = Depends(get_db),
    current_user = Depends(require_role(UserRole.ADMIN))
):
    """Get details of cancelled orders and total amount"""
    reporting_service = ReportingService()
    return reporting_service.get_cancelled_orders(db, start_date, end_date)

@router.get("/reports/average-order-value", response_model=AverageOrderValue)
async def get_average_order_value(
    customer_id: Optional[int] = None,
    restaurant_id: Optional[int] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    db: Session = Depends(get_db)
):
    """Calculate average order value"""
    reporting_service = ReportingService()
    return reporting_service.get_average_order_value(db, customer_id, restaurant_id, start_date, end_date)

@router.get("/reports/peak-times", response_model=PeakTimes)
async def get_peak_times(
    granularity: str = "day",
    db: Session = Depends(get_db)
):
    """Get peak times for orders"""
    reporting_service = ReportingService()
    return reporting_service.get_peak_times(db, granularity)

@router.get("/health")
async def health_check():
    return {"status": "healthy", "service": "reporting-service"}

